ui: mocha-qunit
server: test/test_server.js
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: [25, latest]
  - name: safari
    version: [oldest, latest]
  - name: ie
    version: 9..10
